name: FNWCube
author: AmirVoid12
main: iran.flame.network.cube.GenCubes
version: ${version}
api-version: 1.20
softdepend:
  - Vault
  - ShopGUIPlus
  - Essentials
  - FastAsyncWorldEdit
  - WorldEdit
  - WorldGuard
  - SuperiorSkyblock2
  - PlotSquared
  - AdvancedChests
  - AutoSell
  - ToolsPlus
  - IslandShop
commands:
  gencubes:
    usage: /<command>
    aliases: [gc,gcs]
  cubes:
    usage: /<command>